title: Lane Whitmore's Portfolio
description: Welcome to my page, feel free to bookmark for later as more projects are coming soon including; a web scraping pipeline and NLP classification.
baseurl: 'lanewhitmore.github.io'
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
