title: Lane Whitmore's Portfolio
description: Welcome to my page, feel free to bookmark to see future updates/projects. I am a former English major that began working in the office of a small business presenting data insights on customer tracking that included area maps and more efficient routing for drivers. This sparked my passion for data analysis and led me to the University of San Diego where I learned to code in Python, SQL, and R in addition to learning how machine learning can take business insights and drive value. I have also learned how I can leverage my passion of storytelling to assist my passion for data when building presentations and crafting business stories to assist in driving value in the work place.  

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
